apiVersion: v1
kind: Secret
metadata:
  name: jah-secret
  namespace: jismailns
# Opaque default for abritrary key-value pairs
type: Opaque
data:
  # initial secretvalue: scooby encoded in base64
  secretValue: c2Nvb2J5